### ISSUE TITLE
New users not receiving verification email after registering account

### ISSUE THREAD

**Issue by EvaSchlunke** [pdiveris/sixacts#184]
**Reported by new-users using 'campaigner' link:**

"I signed in by my Google because when I tried to register the confirmation email didn't come through"

"I created an account from my own email but called it Real Democracy Movement. I didn’t get a confirmation email, but seemed to have an account okay. So I posted our proposals”

"Have not received a confirmation email.  It let me login with the details I entered"

Appears that accounts are being created and users are able to submit proposals, but they do not receive confirmation that their accounts have been created.

**Comment by pdiveris** [comment]
Yeah, that's because the queue scheduler was running for beta - can't run both simultaneously. Will switch over now.

Petros Diveris
Sent from Manchester with utter care

E: petros@diveris.org (mailto:petros@diveris.org)
P: +44 7771 608 617 (tel:+44%207771%20608%20617)+44 (0) 161 249 0536 (tel:+44%20(0)%20161%20249%200536) (Fax)
W: http://www.diveris.org

**Comment by EvaSchlunke** [comment]
Doh! Of course.
Excellent.

**Comment by pdiveris** [comment]
Yep, confirmed.
