### ISSUE TITLE
Revisit profile page

### ISSUE THREAD

**Issue by pdiveris** [pdiveris/sixacts#194]
The profile page is problematic. Previous tickets go around the issue(s) bit do not quite address it.

* The link to the profile is not obvious
* To make matters worse, when there is no avatar a boken image is displayed which is
  * ugly
  * clearly not an obvious link to one's pofile
* perhaps the wording of the (welcome) email is not good enough / clear enough

Some thoughts on resolving this
* Show an icon anyway
* Perhaps add an explicit, even **bold**, link at the top just before or after 'Sign in'
* Work a bit on the text of the [page](https://www.sixacts.org/signin)

Any further notes are more than welcome!

**Comment by EvaSchlunke** [comment]
- Agree that 'Profile' button in top menubar after 'Sign in' is a good idea and a necessary addition
- Agree broken link avatar looks ugly. Can we use a generic anonymous avatar icon to replace broken link for users who do not upload photo?
- Can we maintain the avatar/photo as a link to profile even when a 'Profile' button is added (to give people 2 chances to find profile instead of just 1)
- I think wording on https://www.sixacts.org/signin page is fine as is - can't see anyway to improve it

After spending some time today talking people through some basic functions of the site eg.
A user needs to be signed in in order to interact with the site (visitors cannot vote without signing in),
I've decided I need to improve the 'About' page and include some basic instructions to cover these things.
I will do this as a matter of priority.

**Comment by pdiveris** [comment]
I agree on all points and will be working on them straight away.
